# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedlink',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitelink',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
