# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_pageelement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageelement',
            options={'verbose_name': 'Page Element', 'verbose_name_plural': 'Page Elements'},
        ),
    ]
