# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
