# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('req_dt', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('ip_addr', models.CharField(max_length=16, verbose_name='IP Address of Request')),
                ('referer', models.CharField(max_length=255, verbose_name='Referer')),
            ],
        ),
    ]
