# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerequest',
            name='referer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referer'),
        ),
    ]
