# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20171009_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagerequest',
            options={'verbose_name': 'Page Request', 'verbose_name_plural': 'Page Requests'},
        ),
    ]
