# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20171012_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagerequest',
            old_name='req_dt',
            new_name='request_date',
        ),
    ]
