# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50, verbose_name='Your Name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
