# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170925_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
