# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170930_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugged_title',
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
