# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_slugged_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugged_title',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
