# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20171003_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugged_title',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
